#!/bin/bash
set -e

TEMPORARY_DIRECTORY="${HOME?}/temp"

STACK_SOURCE_CODE_ORIGIN="${TEMPORARY_DIRECTORY?}/origin"
STACK_SOURCE_CODE_TARGET="${TEMPORARY_DIRECTORY?}/target"

rm -rf "${STACK_SOURCE_CODE_ORIGIN?}"
rm -rf "${STACK_SOURCE_CODE_TARGET?}"

GIT_REPOSITORY_STACK="terraform-demo-stack"
GIT_REPOSITORY_STACK_LIVE="terraform-demo-live"

. ./clone.sh ${GIT_REPOSITORY_STACK_LIVE?} ${STACK_SOURCE_CODE_TARGET?}

for ENVIRONMENT_DIRECTORY in $(find ./environments/ -type d | sed 1d); do
  ENVIRONMENT=$(basename ${ENVIRONMENT_DIRECTORY})

  TERRAFORM_CONFIGURATION_FILE="${ENVIRONMENT_DIRECTORY}/terraform.tfvars"

  STACK_VERSION=$(cat ${TERRAFORM_CONFIGURATION_FILE?} | hclq get "project.version" -r)

  . ./download.sh ${GIT_REPOSITORY_STACK?} ${STACK_VERSION?} ${STACK_SOURCE_CODE_ORIGIN?}
  . ./release.sh ${ENVIRONMENT} ${STACK_VERSION?} ${STACK_SOURCE_CODE_TARGET?} ${STACK_SOURCE_CODE_ORIGIN?} ${ENVIRONMENT_DIRECTORY?}
  . ./push.sh ${STACK_SOURCE_CODE_TARGET?}
done
